apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-spring-boot
spec:
  replicas: 1 # Number of replicas/instances you want to run
  selector:
    matchLabels:
      app: sample-spring-boot
  template:
    metadata:
      labels:
        app: sample-spring-boot
    spec:
      containers:
      - name: sample-spring-boot-container
        image: anusha1681990/sample-spring-boot:0.0.1-SNAPSHOT
 # Replace with your Angular image and tag
        ports:
        - containerPort: 8080 # Port where your Angular app runs
